import Head from 'next/head'
import NavAdvert from '../components/molecules/advertisement/NavAdvert'
import ResultsAdverts from '../components/molecules/advertisement/ResultsAdverts'
import Header from '../components/organisms/header/Header'

export default function Advert({adverts}) {

  console.log(adverts)

  return (
    <div>
        <Head>
            <title>AutoRate</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header/>

        <NavAdvert/>
        
        <ResultsAdverts adverts={adverts}/>

    </div>
  )
}

export async function getServerSideProps() {
  const request = await fetch("http://localhost:4000/advert")
  .then((res) => res.json())

  return {
    props: {
      adverts: request
    }
  }
}