import Head from 'next/head'
import Bandeau from '../components/molecules/Bandeau'
import Header from '../components/organisms/header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AutoRate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <Bandeau />
    </div>
  )
}
