import React from 'react'
import Header from '../components/organisms/header/Header'
import Head from 'next/dist/next-server/lib/head'
import ProfileUser from '../components/organisms/profile/ProfileUser'

function profile() {
    return (
        <div>
            <Head>
                <title>AutoRate</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>

            <ProfileUser/>
        </div>
    )
}

export default profile
