import Head from 'next/head'
import React from 'react'
import FormAdvert from '../../molecules/advertisement/FormAdvert'
import Header from '../header/Header'

function CreateAdvertPage() {
    return (
        <div>
            <Head>
                <title>LaBonneCote</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <FormAdvert/>
        </div>
    )
}

export default CreateAdvertPage
